# Generated by Django 4.1.1 on 2022-12-22 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Maxsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('malumoti', models.TextField()),
                ('soni', models.PositiveIntegerField(default=0)),
                ('narxi', models.PositiveIntegerField(default=0)),
                ('aksiya', models.BooleanField(default=False)),
                ('aksiya_n', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('sana', models.DateField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='alle_images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alles.turi')),
            ],
        ),
    ]
